services:
  - type: web
    name: the-crate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: RATING_DATABASE_ID
        sync: false
